### ISSUE TITLE
Use GNOME notifications

### ISSUE THREAD

**Issue by zedtux** [Douane/Douane#26]
Just an idea to be investigated:

GNOME (shell) has an amazing notification center which could be used instead of the douane dialog box.

**Comment by ssokolow** [comment]
I had a long detailed post with lots of citations but Douane froze my kernel an hour after being installed when my desktop normally stays logged in and running for a month or two at a time. As such, here's the rushed rewrite...

**First,** Remove the "Use the Allow or Deny button." That's obvious from the combination of Allow and Deny buttons with the "Spotify wants..." message and saying it like that just clutters things up and makes the reading more burdensome for tired, distracted, or dyslexic people. (You don't see every dialog box saying "Use the Cancel or OK button.")

I'm sure there's an entry to that effect in the GNOME HIG but I don't have time to go searching for it.

(Also, "Internet" is a proper noun, so it should be capitalized.)

**Second,**  if possible, put Allow to the right of Deny to follow the "OK to the right of Cancel" convention in GNOME to avoid the risk of people's muscle memory leading them astray. ([[See also, this](http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/))

**Third,** you don't need to "implement for others" or write something that can be used "instead of the douane dialog box". Desktop notifications are standardized and it's possible to detect whether the desktop's notification host supports action buttons.

https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html

Luckily, I wasn't typing the example code in the browser, so it survived:

```python
#!/usr/bin/env python3

import signal, sys
from gettext import gettext as _
from xml.sax.saxutils import escape

import notify2
from gi.repository import Gtk

class NotificationExample(object):
    notify = None
    notifications = {}
    supports_body = False

    def __init__(self):
        if self.init_notifications():
            self.notify = self.notify_notifications
        else:
            self.notify = self.notify_dialog

    def init_notifications(self):
        if not notify2.init('Douane', mainloop='glib'):
            return False

        caps = notify2.get_server_caps()
        self.supports_body = 'body' in caps

        if 'actions' not in caps:
            return False

        return True

    def notify_notifications(self, app):
        msg = _("{0} wants to connect to {1}").format(
                escape(app), "the Internet or local network.")

        if self.supports_body:
            summary = 'Douane'
            body = msg
        else:
            summary = msg
            body = ''

        note = notify2.Notification(summary, body,
            "/opt/douane/data/douane_128.png")
        note.set_category("network")
        note.set_timeout(notify2.EXPIRES_NEVER)
        note.set_urgency(notify2.URGENCY_CRITICAL)

        note.add_action("allow", _("Allow"), self.cb_allow)
        note.add_action("deny", _("Deny"), self.cb_deny)

        note.set_hint_string("sound-name", "dialog-question")
        # note.set_hint_string("desktop-entry",
        #                      "/path/to/douane-dialog.desktop")

        self.notifications[note] = app
        note.show()

    def notify_dialog(self, app):
        print("TODO: Code for existing dialog-based notification")
        sys.exit()

    def cb_allow(self, note, action):
        print(_("Allowed {0}").format(self.notifications[note]))
        Gtk.main_quit()

    def cb_deny(self, note, action):
        print(_("Denied {0}").format(self.notifications[note]))
        Gtk.main_quit()

if __name__ == "__main__":
    Gtk.init(sys.argv)
    example = NotificationExample()
    example.notify("Spotify")

    # Ensure we can kill the example with Ctrl+C
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    Gtk.main()
```

That's how to make it as robust as I know how to do and, if my intuition about how GNOME Shell is mapping fields to display output is correct (I've never used it), then it should look like yours under GNOME (aside from the corrections I listed). Here's what it looks like on my KDE desktop:
![screenshot3](https://cloud.githubusercontent.com/assets/46915/11917422/3486c0c2-a6d4-11e5-9cee-12d15b5e22f9.png)

**Comment by zedtux** [comment]
Thank you @ssokolow for the update on this ticket, and sorry for the kernel crash x-|

**Comment by zedtux** [comment]
Sorry @intika I don't have it anymore but it was a very simple one, just to show the notification, it wasn't implementing the action buttons.

**Comment by intika** [comment]
@zedtux :+1:

**Comment by zedtux** [comment]
@intika I found the python script I did in the past used to make those screenshots :)


[notif.py.zip](https://github.com/Douane/Douane/files/1935272/notif.py.zip)

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/26).
