### ISSUE TITLE
flatpak

### ISSUE THREAD

**Issue by alexstaj** [Douane/Douane#62]
can you package this for flakpak please.

see flatpak.org

**Comment by zedtux** [comment]
Thank you @alexstaj for your issue. I don't take care of packaging, but in case someone could do it, I'll be more than happy to update the website then with the package instructions.

**Comment by mauron85** [comment]
The question is if kernel modules can be packaged as flatpak/snaps. If not then only dialog and daemon and configurator can be packged.

**Comment by zedtux** [comment]
Good point @mauron85 👍

**Comment by intika** [comment]
an appimage could be possible, but a flatpak it's kind a weird...
1. - Flatpak is a container like a virtualbox, using douane on the host will do the job but using it inside a flatpak is useless because flatpak separate the packages from each other so douane will have no effect on other apps  
2. - Loading the kernel module in a userspace will limit its action to the userspace that run the module, so yes loading the kernel module with flatpak is possible but will be usable only for the pack itself only in other work its like having a virtualmachine with douane inside and nothing else. 
3. - what will be the purpose of having a flatpak ? i don't see the point here... easy install ? then appimage instead

the main problem with flatpack is its sandboxing feature, of course every thing is possible in IT we could disable/hack/rule the flatpak sandboxing but its like using a pen as a knife... 

Conclusion : yes possible but not efficient and require a lot of work that could be dedicated to make the product better

**Comment by zedtux** [comment]
Thank you @intika for your input. I don't know at all this technology and your explanations looks clear to me.

**Comment by intika** [comment]
:+1:

**Comment by intika** [comment]
this issue should be closed

**Comment by zedtux** [comment]
@alexstaj any input or shall we close this issue?

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/62).
