### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by Henrietta1989** [Douane/Douane#70]
I'm new at GitHub and i'm confused if Douane is still being actively developed??

Last commit is 27 Apr 2014 but wiki and issues page has some activity.

So is Douane still safe to use in Raspbian and where i can download latest version?

Thanks

**Comment by zedtux** [comment]
Hello @Henrietta1989,

I'm working on other projects so I'm not continuing to develop Douane for now, but the project is not abandoned.

When people are contributing, I'm taking the required time to help and make it happening.
I'm planning to come back on Douane one day but for now I have a very big project taking all my time.
Sorry about that.

The latest version is the version in Github. As of today, only on Archlinux there were a package (which is broken as far as I understood) but no body else contributed to the packaging.
If you have some skills and want to package Douane for a distro, please feel free to notify me and I'll update the douaneapp.com website.

Otherwise, in order to install it, please follow [the compilation instructions](https://github.com/Douane/Douane/wiki/Compilation) (not that hard).

**Comment by Henrietta1989** [comment]
Thanks. Unfortunately i'm total newbie in programming so i can't help.

Gufw is the only similar firewall GUI app i know which runs in Raspbian and is actively kept up to date.

Are there any other?

And if i install your app, how safe it is to use these days?

**Comment by zedtux** [comment]
> Thanks. Unfortunately i'm total newbie in programming so i can't help.

Learning packaging is something not that hard and is really helpful.

> Gufw is the only similar firewall GUI app i know which runs in Raspbian and is actively kept up to date.

Gufw is different from Douane, or actually Douane is different from all other firewall app on Linux. Douane is working at application level while all the others are working on the network level.

Are there any other?

`iptables` ?

> And if i install your app, how safe it is to use these days?

The applications is working, laking of features, and there a known performance issue on the daemon process but it's okay to use it I think so.

**Comment by Henrietta1989** [comment]
How bad that performance issue is? I probably would install it if it don't eat CPU away. Could you fix it?

**Comment by zedtux** [comment]
> How bad that performance issue is?

The daemon process is not eating the CPU but the RAM. There a place where it seems I'm not cleaning the memory and the memory usage of the daemon process is growing slowly but continuously.
The means the daemon process needs to be restarted (no problem, you'll not lose any data) like everyday, depending on your network usage :)
