### ISSUE TITLE
douane-dialog call failed error

### ISSUE THREAD

**Issue by arterhacker** [Douane/Douane#72]
hi everyone, what is the problem exactly?

```
anonymous:~/Douane/douane-dialog$ /opt/douane/bin/douane-dialog &
[1] 21774
anonymous:~/Douane/douane-dialog$ log4cxx: setFile(/var/log/douane.log,true) call failed.
log4cxx: IO Exception : status code = 13
log4cxx: setFile(/var/log/douane.log,true) call failed.
log4cxx: IO Exception : status code = 13
log4cxx: No output stream or file set for the appender named [].
^C

```

**Comment by zedtux** [comment]
Hello @arterhacker,

Your error seems to be related to permissions to me. Can you please show the output of `ls -al /var/log/douane.log`?

**Comment by arterhacker** [comment]
Sure. Here is:

```anonymous:~$ ls -al /var/log/douane.log
-rw-r--r-- 1 root root 322 Mar 26 12:12 /var/log/douane.log
```

**Comment by zedtux** [comment]
Okay so I think I figured out what is your issue.

I do believe you ran the dialog process with sudo once, which you shouldn't otherwise the file is owned by the root user and then you tried to run it again but without sudo which leaded you to the permission issue.

So first thing, I would suggest you to either kill the `/var/log/douane.log` file or change the owner of the file to you and then run without sudo only the dialog process.

Then regarding the `Exiting Douane dialog with signal 2` error, you have then to look at the `/var/log/douane.log` file content in order to better understand what's wrong.
(I can help you if you post the file content, like in a gist)

**Comment by arterhacker** [comment]
I've removed all douane files after use the "cleandkms" command. (dkms cleared successfully too). then, I've installed douane again, here is the steps and results:
https://gist.github.com/arterhacker/6bc55b27a4f42001ecf7a8f321b02492

you can see errors on last lines. after these errors, I've created a file called "douane.log" then I've changed this file's chown to my user. there is no error now. but nothing seems and nothing happens.  

```
anonymous:~$ /opt/douane/bin/douane-dialog &
[1] 26872
anonymous:~$ fg
bash: fg: this process is finished.
[1]+  Bitti                   /opt/douane/bin/douane-dialog
anonymous:~$ 
```

**Comment by zedtux** [comment]
Have you deleted the douane.log file?

**Comment by arterhacker** [comment]
Ups, yes. as I said before, I've deleted all Douane files. So, this process includes the log file too. But then, I've created the log file again and changed the ownership.

**Comment by zedtux** [comment]
Is creating the file and changing the ownership solving your issue?

The file created by the application will be the same as the one of the running application so that if you run it with your account, it shouldn't fail with a permission denied issue.

What Linux distro are you using? (`lsb_release -a` ?)

**Comment by arterhacker** [comment]
> Is creating the file and changing the ownership solving your issue?

after creating the file and changing the ownership, there is no error anymore. douane log is just saying that:

`03/04/2017 14:29:40  INFO: The log file is /var/log/douane.log`

and no more entry for this process. also, `$ /opt/douane/bin/douane-dialog` process is still waiting without error, but dialog window isn't appear. I've tried many thing, but nothing solves. There is no error now, just dialog window isn't opening.

my distro: ubuntu 16.04 xenial

more detail is here:
```
anonymous:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

-------
I've installed ZORIN OS to my another computer then tried again to install your program, first, it didn't create the "douane.log" file again, like in my other installation on Ubuntu 16.04. I've created douane.log file again with sudo permission (because I'm creating a file on /var/log/ directory) then I've changed the ownership again, it was OK too, then I've tried again to run douane-dialog but it didn't appeared like in my other installation. that was exactly same and douane.log file is just saying that again: "`03/04/2017 14:48:40  INFO: The log file is /var/log/douane.log`". 

I don't know why is this happening.. but I was followed your steps as like in compilation page of your wiki. 

(Uh! Except one thing!)

I've installad gtkmm packages because you didn't specified that on the dependencies page of your wiki and your program needs gtkmm packages. So, I've installed gtkmm with this commands:

```
libgtkmm-3.0-dev
libgstreamermm-1.0-dev
```

**here is a notice about it:**
I've got some warnings during use "make" command in douane-daemon and douane-dialog directories but I was thinking that you already know these warnings and  they're not important. But now, my think is changed. maybe they're important and you want to see them. [here is on gist](https://gist.github.com/arterhacker/6beb8f764bcaaf8bc40c2ce1862e6c16)

**Comment by arterhacker** [comment]
Here are additional informations:

I've followed debugging steps, 

```
anonymous:~$ /opt/douane/douaned -D
bash: /opt/douane/douaned: Access denied
anonymous:~$ sudo chown myusername:myusername /opt/douane/
anonymous:~$ sudo chown myusername:myusername /opt/douane/*
anonymous:~$ /opt/douane/douaned -D
terminate called after throwing an instance of 'DBus::Error'
  what():  Connection ":1.120" is not allowed to own the service "org.zedroot.Douane" due to security policies in the configuration file
Cancelled 
anonymous:~$ 
```

Also, I get an crash report after that. Crash title is: `douaned crashed with SIGABRT in __gnu_cxx::__verbose_terminate_handler()`

**Comment by arterhacker** [comment]
Here is [new detail](https://gist.github.com/arterhacker/1af73b97a78f667e31816b9b2fe6b035)

**Comment by arterhacker** [comment]
Here is [new detail](https://gist.github.com/arterhacker/c6693716ea4d5fd8b9f16fa9331280ce)

**Comment by zedtux** [comment]
Nice comments @arterhacker :)

Based on [your previous comment](https://github.com/Douane/Douane/issues/72#issuecomment-291129258) it seems that something prevented the installation of the [org.zedroot.Douane.conf](https://github.com/Douane/douane-daemon/blob/master/system.d/org.zedroot.Douane.conf) file (It is supposed to be in the folder `/etc/dbus-1/system.d/`. Can you please check that?).

Another comment: In general you seem to work in a very limited environment which causes all those troubles. When I see what you posted in [a previous comment](https://github.com/Douane/Douane/issues/72#issuecomment-291129258), it looks really strange.
BTW can you please show the output of `ls -al` before to change permissions?

**Comment by arterhacker** [comment]
>Based on your previous comment it seems that something prevented the installation of the org.zedroot.Douane.conf file (It is supposed to be in the folder /etc/dbus-1/system.d/. Can you please check that?).

Yep, it is here:
```
anonymous:/etc/dbus-1/system.d$ ls | grep "org.zedroot"
org.zedroot.Douane.conf
anonymous:/etc/dbus-1/system.d$ ls -al org.zedroot.Douane.conf
-rw-r--r-- 1 root root 681 Apr  3 15:12 org.zedroot.Douane.conf
anonymous:/etc/dbus-1/system.d$ 
```

>BTW can you please show the output of ls -al before to change permissions?
Sure. I've installed everything again to show you the permissions. 

**Here is the output while install it:**
```
anonymous:~/Douane/douane-daemon$ sudo make install
[sudo] password for anonymous: 
test -d /opt/douane || mkdir -p /opt/douane
test -d /etc/init.d/ || mkdir -p /etc/init.d/
test -d /etc/dbus-1/system.d/ || mkdir -p /etc/dbus-1/system.d/
install -m 0500 douaned /opt/douane
install -m 0755 init.d/douane /etc/init.d/
install -m 0644 system.d/org.zedroot.Douane.conf /etc/dbus-1/system.d/
```
You can see the douaned file here too. 

**Also, here is the permissions after installation:**
```
anonymous:~$ ls -al /opt/douane/douaned
-r-x------ 1 root root 11996480 Nis  4 10:34 /opt/douane/douaned
```

I guess, there is a problem about permission. :) But I assure you, I've tried what did you said in the compile page of the wiki.

**Comment by zedtux** [comment]
Aha, I think I understood what's wrong.

The `douaned` process is installed and accessible only by `root` on purpose, and you should not change its permissions.
You *must* use the systemd script in order to start the daemon so that it run as root.
If I'm not mistaking, I think you're trying to run it yourself, using your username, am I right?

The _normal_ way of using Douane should be the following:

1. Run the douane configurator
2. Enable the firewall
3. Enter your password
4. Start an unknown application

And this should be it to have it starting  to popup the dialog window.

Can you please tell me if is this what you're doing or if this solve your issue?

**Comment by arterhacker** [comment]
Uh, yes, I guess something is solved  but not completely :p

After start the douane from terminal, it blocked everything as you know, then I checked with tail comment, I saw that it working and saying that: "no rules", also checking the apps.

Then I tried to run this command: `/opt/bin/douane/douane-dialog &` and it worked in this case! :) Sorry if there is a problem caused by me).  

**OK but some icons aren't appering now:**

![ss](https://cloud.githubusercontent.com/assets/24942169/24655309/6ce51366-1946-11e7-8c8d-66fa4833a1fd.png) (look at top right, there is a big icon and it is missing)

One more thing, douane app (maybe it was douane-configurator) isn't showing in apps, I guess it didn't create a .desktop file. But I can start it with `$ douane-configurator` command, it's okay.

and thanks thanks thanks

**Comment by mauron85** [comment]
Hi zedtux. Thank you for douane, it's awesome. I think I've same issue with Ubuntu 16.04.
Daemon is running under root user. And dialog is started from autostart desktop file as me. I've changed permissions of log file to me. But dialog was not popping up. So I've killed dialog, and tried to start it from terminal. Dialog didn't show permission error, but it will fail to connect to dbus (not sure) and it ends with some timeout error. But if I run it as root (with sudo) it works just fine. So my question is, has to be dialog user also root?

**Comment by zedtux** [comment]
@mauron85 the daemon process must run as root, otherwise it will not be able to communicate with the kernel module.

Regarding the dialog process, it should run using the logged in user as DBus allow publishing methods from a process running as root to be executed from a non root user.

Now, it could be that Ubuntu has changed this behaviour, or the DBus project changed their mind about this...

Regarding the `policy user='root'` from the XML file, this file is used by the daemon process in order to publish the daemon methods to be accessible by the dialog process, and as the daemon process runs as root, the definition in DBus uses the root user.

**Comment by mauron85** [comment]
@zedtux that explains why I failed with running daemon under special non-root user. I've created user 'douane' with no priviliges and set init script to run daemon as that user.
