### ISSUE TITLE
Problem with KeePass2

### ISSUE THREAD

**Issue by samic130** [Douane/Douane#77]
Everything works fine on my system. (Linux Mint 17.3 Cinnamon with Kernel 3.19.0)
It asked for permisson for Firefox and etc and I allowed and it worked.
Then I ran keepass2 and it asked for a connection for "/usr/bin/mono-sgen". I denied and keepass didn't run.
Since then I can't run keepass unless I stop the Dounane service.
I even deleted that deny rule but it didn't help.
Here is the log:

```
22/01/2018 16:01:13 | daemon | DEBUG | [netlink_message_handler.cpp::NetlinkMessageHandler:7]: [lo] TCP 127.0.0.1:50399 -> 127.0.0.1:50462 with a size of 60 for process /usr/bin/mono-sgen
22/01/2018 16:01:13 | daemon | DEBUG | [rules_manager.cpp::RulesManager:27]: No rule found for /usr/bin/mono-sgen
22/01/2018 16:01:13 | daemon |  INFO | [rules_manager.cpp::RulesManager:57]: Currently 1 pending rules
22/01/2018 16:01:13 | daemon | DEBUG | [dbus/dbus_server.cpp::DBusServer:48]: DBusServer::signal_new_unknown_activity...
22/01/2018 16:01:13 | daemon | DEBUG | [dbus/douane.cpp::Douane:58]: Douane::emit_new_activity_to_be_validated_signal...
22/01/2018 16:01:13 | daemon | DEBUG | [dbus/douane.cpp::Douane:66]: Firing D-Bus signal NewActivityToBeValidated...
```

My keepass2 version is: 2.25+dfsg-1ubuntu0.1

**Comment by zedtux** [comment]
Thank you @samic130 for your issue.

As the no rules was found from the kernel module, the connections for `/usr/bin/mono-sgen` are queued, meaning not dropped but kept a side, and the dialog process should popup and ask you if you want to allow/deny the connection.

The extract of the logs you gave shows logs only from `daemon`. It is now interesting to have the logs from `dialog` in order to understand what is happening.

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/77).
