### ISSUE TITLE
Douane doesn't start on boot

### ISSUE THREAD

**Issue by saitam1** [Douane/Douane#79]
I have switched on the button in the configurator for `Auto start Douane on boot` and the button is also active after a computer restart, but Douane itself isn't active. All my programms have internet access.

![douane](https://user-images.githubusercontent.com/23245678/36266044-e258dc58-1270-11e8-8132-766c59de02ea.png)

How to handle this?

**Comment by zedtux** [comment]
Thank you @saitam1 for this issue.

I do know that this feature isn't working for everybody. When I started Douane, `systemd` wasn't yet ready, then with upgrades, it came and I did updated the project, but seems to not work all the time.

Can you please check the Douane logs in order to see any kind of information that would help?

**Comment by intika** [comment]
i added a pull request to solve that problem
can you check with new version 
or just add `# chkconfig: - 01 99` to the file /etc/init.d/douane just before description

**Comment by zedtux** [comment]
This repo has moved to GitLab and this issue has been imported. You can access it [here](https://gitlab.com/douaneapp/Douane/issues/79).
