### ISSUE TITLE
Uninstall Douane

### ISSUE THREAD

**Issue by saitam1** [Douane/Douane#81]
Is there somewhere an instruction on how to `uninstall` Douane if it continue not to work correctly  ?

**Comment by zedtux** [comment]
Thank you @saitam1 for this issue.

No, I never took the time to write one, but basically you have to:

- Remove the configurator folder
- Delete the daemon and the dialog processes
- Use the `dkms uninstall` command in order to remove the kernel module (Have a look at [this SO question](https://askubuntu.com/questions/849547/how-do-i-uninstall-dkms-modules-if-there-are-two-of-them) to have an idea)

If you want to write a wiki page to explain how to do it, please feel free to do it.
