### ISSUE TITLE
What network communications is supported 

### ISSUE THREAD

**Issue by intika** [Douane/Douane#88]
It would be nice to have a section "supported com" or something on the wiki that describe what is supported and what's not 

i don't know enough your code to be able to answer that question fully but for now i know 

Supported :
- Support any outgoing connection generate by application/library
- Supported Protocols : TCP/UDP/ICMP ... and ? raw ?
- Supported Direction : Outgoing - Listening 

Not Supported : 
- Kernel connections : netbios/l2tp/etc...
- iptables (not used by douane, but could be run side by side with douane)
- Incoming connections : (use iptables for that)

Can you please complete the list and or correct me ?... also would it be useful to add what network function are used in the kernel module or not ?

**Comment by zedtux** [comment]
Douane is an application firewall preventing unknown applications to send data, so it is outgoing only (as of now) direction.

Regarding the rest, the kernel module is using the Linux Kernel NetFilter module in order to catch the network packets before there are routed to the network card. Any packets going through this module are watched by Douane.

So to summarise, Douane is simply filtering userspace application network traffic based on simple allow/deny rules and that's it.
I'm not an expert but I do believe that an application creating a network socket should go through the NetFilter kernel module and should be filtered by Douane.

If you want to do something different than what has been described bellow, please explain what you want to do / add and I can give my feedback ;)

**Comment by intika** [comment]
okay i will update the read me
